#!/bin/bash

echo "=== Cafe Games Deployment Helper ==="
echo ""
echo "1. Frontend Deployment (Vercel)"
echo "   Run the following command:"
echo "   npx vercel"
echo ""
echo "2. Backend Deployment (Firebase)"
echo "   Ensure you have the Firebase CLI installed:"
echo "   npm install -g firebase-tools"
echo ""
echo "   Login to Firebase:"
echo "   firebase login"
echo ""
echo "   Initialize Firebase in this directory (if not done):"
echo "   firebase init functions"
echo ""
echo "   Deploy Functions:"
echo "   firebase deploy --only functions"
echo ""
echo "3. Post-Deployment"
echo "   Update 'src/lib/api.ts' to point to your real Firebase Function URLs instead of the mock implementation."
echo ""
echo "Done!"
